### ISSUE TITLE
README instructions are insufficient

### ISSUE THREAD

**Issue by jdmarshall** [GoogleChromeLabs/json-parse-benchmark#6]
npm run bench fails because none of the applications it is looking for are in the PATH.

**Comment by mathiasbynens** [comment]
The missing step is probably to add `jsvu`’s binaries to the `PATH` per <https://github.com/GoogleChromeLabs/jsvu#installation>:

> Modify your dotfiles (e.g. `~/.bashrc`) to add `~/.jsvu` to your `PATH`:
> 
> ```sh
> export PATH="${HOME}/.jsvu:${PATH}"
> ```
